version: '3.8'

services:
  app:
    restart: always
    build: .
    ports:
      - '3001:3001'
    links:
      - postgres
    volumes:
      - './src:/usr/src/app/src'
      - './node_modules:/usr/src/app/node_modules'
  postgres:
    image: postgres
    ports:
      - '5432:5432'

